[project]
name = "mistral-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "huggingface-hub>=0.36.0",
    "mistral-common>=1.8.8",
    "transformers>=4.57.6",
]
